config/routes.rb
Hoipolloi::Application.routes.draw do
  resources :conversations do
    post 'read', on: :collection, as: 'read'
    post 'reply', on: :member, as: 'reply'
  end

  # Omniauth
  get '/auth/twitter/callback', to: 'sessions#create'
  delete '/auth/logout', to: 'sessions#destroy'

  post '/rape', to: 'rapes#create', as: 'rape'

  # Root route
  root 'home#index'
end

app/models/conversation.rb
# A conversation -- a series of tweets in order
class Conversation < ActiveRecord::Base
  belongs_to :user
  has_many :tweets

  class << self
    # There's gotta be a better way of doing this...
    def recent_conversations limit, current_user, newer_than = false
      scope = self.order('(SELECT MAX(tweeted_at) FROM tweets WHERE (conversations.id=tweets.conversation_id)) DESC')
                  .limit(10)
                  .includes(:tweets)
                  .where("tweets.from_name != '#{current_user.nickname}'")
                  .where(user_id: current_user)

      if newer_than
        scope = scope.where("conversations.created_at > '#{newer_than || '0000-00-00 00:00:00'}'")
      end

      scope.all
    end

    def most_recent_conversation current_user
      self.order('created_at DESC').where(user_id: current_user).limit(1).first
    end
  end

  # Grab a sentence of the the list of people we're conversing with
  def from_names(current_user)
    get_from_names(current_user).to_sentence
  end

  # Same as above, only not a setence and with @ symbols
  def from_names_at(current_user)
    get_from_names(current_user).map { |n| "@#{n}" }.join(' ')
  end

  # Grab a snippet of the conversation
  def snippet
    tweets.order('tweeted_at DESC').first.text
  end

  private

  # Fetch all the tweeter's names
  def get_from_names(current_user)
    tweets.where("tweets.from_name != '#{current_user}'").map(&:from_name).uniq
  end
end

app/models/user.rb
# A user that has signed up for the site
class User < ActiveRecord::Base
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :auto_refresh
  before_action :configure_twitter

private
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def auto_refresh
    @auto_refresh
  end

  def configure_twitter
    if current_user && session[:access_token] && session[:access_token_secret]
      Twitter.configure do |config|
        config.consumer_key = ENV.fetch('TWITTER_CONSUMER_KEY')
        config.consumer_secret = ENV.fetch('TWITTER_CONSUMER_SECRET')
        config.oauth_token = session[:access_token]
        config.oauth_token_secret = session[:access_token_secret]
      end
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @conversations = Conversation.recent_conversations 10, current_user
    @auto_refresh = true
  end

  def show
    @conversation = Conversation.find params[:id]
    @conversation.update_attributes :read => true
  end

  def reply
    @conversation = Conversation.find params[:id]

    tweet = Twitter.update params[:reply], :in_reply_to_status_id => @conversation.tweets.order('tweeted_at DESC').first.tweet_id
    @conversation.tweets.create :text => tweet.text, :tweet_id => tweet.id, :user => @current_user, :from_name => @current_user.nickname, :tweeted_at => tweet.created_at

    redirect_to conversation_url(@conversation)
  end

  def read
    if params[:mark_as_read]
      Conversation.update_all({ :read => true }, { :id => params[:conversations] })
    elsif params[:mark_as_unread]
      Conversation.update_all({ :read => false }, { :id => params[:conversations] })
    end
    redirect_to conversations_url
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to conversations_url
    end
  end
end

app/controllers/rapes_controller.rb
## --------------------------------------------------------------
## Tweet raping!

# Go and rape Twitter for the user's latest tweets,
# and return a lovely HTML snippet for us
class RapesController < ApplicationController

  def create
    # First, we're going to grab the user's recent tweets and import them into
    # the database. We're doing this so that we can create conversations around them.
    current_tweet = current_user.tweets.order('tweeted_at DESC').where('from_name' => current_user.nickname).first
    current_conversation = Conversation.most_recent_conversation current_user

    unless current_tweet.nil?
      my_tweets = Twitter.user_timeline :since_id => current_tweet.tweet_id
    else
      my_tweets = Twitter.user_timeline
    end

    # We now want to loop through our tweets and bring them into the database.
    import_into_database my_tweets

    # Now, let's do the same sort of thing for our mentions!
    current_mention = current_user.tweets.order('tweeted_at DESC').where("from_name != '#{current_user.nickname}'").first

    unless current_mention.nil?
      mentions = Twitter.mentions :since_id => current_mention.tweet_id
    else
      mentions = Twitter.mentions
    end

    import_into_database mentions

    # Finally, grab our recent conversations
    @conversations = Conversation.recent_conversations 10, current_user

    # ...and render out our view :)
    render @conversations, layout: false
  end

private

  # Import our tweets into the database. But be clever about it, yeah? Check that
  # if we're replying to a tweet and we have that tweet in our database, we add it
  # to that conversation, or if we don't, we create a new conversation for it.
  def import_into_database tweets
    tweets.each do |tweet|
      begin
        unless tweet.in_reply_to_status_id.nil?

          # I've been battling DataMapper all night. I know this is horrible, and that Satan will
          # banish me to Hell for this. Oh! I can smell the burning flesh, the intoxicating smoke,
          # the reams and reams of Dan Brown novels. But alas, my hands are tied.
          #
          # conversation = Conversation.first :limit => 1, :tweets => { :tweet_id => tweet.in_reply_to_status_id }
          conversation_tweet = Tweet.find_by_tweet_id(tweet.in_reply_to_status_id, :include => [ :conversation ])

          unless conversation_tweet.nil?

            # If we have any existing tweets, we have a conversation!
            conversation = conversation_tweet.conversation
          else

            # Otherwise, we need to create a new conversation
            conversation = Conversation.create! :read => 0, :user => current_user, :start_tweet_id => tweet.id
          end
        else

          conversation = Conversation.create! :read => 0, :user => current_user, :start_tweet_id => tweet.id
        end

        # Import the tweet into the database.
        Tweet.create! :tweet_id => tweet.id,
                      :from_name => tweet.user.screen_name,
                      :user => current_user,
                      :conversation_id => conversation.id,
                      :text => tweet.text,
                      :tweeted_at => tweet.created_at
      rescue ActiveRecord::RecordNotUnique => e
        # ignore the duplicate
      else
        conversation.update_attributes :read => 0
      end
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]

    session[:access_token] = auth['credentials']['token']
    session[:access_token_secret] = auth['credentials']['secret']
    session[:username] = auth['info']['nickname']

    user = User.find_or_create_by_uid :uid => auth["uid"],
                                      :nickname => auth["info"]["nickname"],
                                      :name => auth["info"]["name"],
                                      :created_at => Time.now
    session[:user_id] = user.id

    redirect_to root_url
  end

  def destroy
    session[:user_id] = session[:username] = session[:access_token] = session[:access_token_secret] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/_conversation.html.erb
<tr<% unless conversation.read %> class="unread"<% end %> data-conversation-id="<%= conversation.id %>">
  <td class="selected-column"></td>
  <td><input type="checkbox" name="conversations[]" value="<%= conversation.id %>" /></td>
  <td><%= conversation.from_names current_user.nickname %></td>
  <td><%= link_to conversation.snippet, conversation_path(conversation) %></td>
</tr>

app/views/conversations/index.html.erb
<%= form_tag read_conversations_path, method: 'post' do %>
  <div class="span8 offset2">
    <table class="table table-striped table-bordered" id="conversations-table">
      <tbody id="conversations" class="load-from-server" data-remote-url="<%= rape_url %>">
        <%= render @conversations %>
      </tbody>
    </table>

    <p>
      <input class="btn pull-left" type="submit" name="mark_as_read" value="Mark as read" />
      <input class="btn pull-left" type="submit" name="mark_as_unread" value="Mark as unread" style="margin-left:5px" />
    </p>
  </div>
<% end %>

app/views/conversations/show.html.erb
<div class="span8 offset2">
  <h3 id="conversation_tagline">Conversation with <%= @conversation.from_names(current_user.nickname) %></h3>

  <div id="tweets">
    <div class="new-tweet">
      <%= form_for [:reply, @conversation], method: 'post' do %>
        <p class="triangle-border right">
          <textarea name="reply"><%= @conversation.from_names_at(current_user.nickname) %> </textarea>
        </p>
        <p class="author me">
          <img src="https://api.twitter.com/1/users/profile_image/<%= current_user.nickname %>?size=bigger" width="75" height="75" />
          <strong>@<%= current_user.nickname %></strong>
        </p>

        <p class="buttons">
          <input type="submit" value="Reply" class="btn" />
        </p>
      <% end %>
    </div>

    <% for tweet in @conversation.tweets.order('tweeted_at DESC') %>
      <div class="tweet">
        <p class="author <% if tweet.from_name == current_user.nickname %>me<% else %>them<% end %>">
          <img src="https://api.twitter.com/1/users/profile_image/<%= tweet.from_name %>?size=bigger" width="75" height="75" />
          <strong>@<%= tweet.from_name %></strong>
        </p>

        <p class="text triangle-border <% if tweet.from_name == current_user.nickname %>right<% else %>left<% end %>"><%= tweet.output_text %></p>
      </div>
    <% end %>
  </div>
</div>